services:
  db:
    container_name: spotify-reviews-db
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: spotify-reviews
    volumes:
      - spotify-reviews-db-data:/var/lib/mysql
  backend:
    container_name: spotify-reviews
    build: .
    restart: unless-stopped
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
      FRONTEND_URL: ${FRONTEND_URL}
      JWT_SECRET: ${JWT_SECRET}

volumes:
  spotify-reviews-db-data: {}
